export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_DATA_FOLLOW = 'SOCKET_DATA_FOLLOW';
export const SOCKET_DATA_UNFOLLOW = 'SOCKET_DATA_UNFOLLOW';
export const SOCKET_DATA_INIT = 'SOCKET_DATA_INIT';
export const SOCKET_DATA_CHANGE = 'SOCKET_DATA_CHANGE';
